### ISSUE TITLE
Set up pep8 checking for travis-ci

### ISSUE THREAD

**Issue by nkoep** [j-towns/pymanopt#13]
In the interest of code consistency I'd like to propose to add pep8 checks to travis:
```yaml
before_install:
    - pip install pep8

script:
    - find . -name \*.py -exec pep8 {} +
```
While it might be a bit extreme to enforce this via CI, I believe that a consistent coding style goes a long way in ensuring that code remains readable as the code base grows. The less strict or invasive way would be to add a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) file to the repo with suggested guidelines (which we might want to do in any case).

After cleaning up the code base just a few weeks ago (see 5b04895c28aed6af7548bf1a2558e19a0eb6b3b2 and e1248f01c03f3eed14e693824128054be4a474ff), I was quite surprised to see that there are now over 60 new warnings again. Ideally I'd like to avoid changes like this in the future.
